'use client';

import { useState } from 'react';
import { useAuth } from '@/hooks/use-auth';
import TopBar from '@/components/layout/TopBar';
import ResourceState from '@/components/data/ResourceState';
import { useApiResource } from '@/hooks/use-api-resource';
import { listMedications, openControlledRegister, recordControlledMovement } from '@/lib/api/pharmacy';

export default function ControlledSubstancesPage() {
  const { user, isLoading: authLoading } = useAuth(); const { data, isLoading, error, reload } = useApiResource((signal) => listMedications({ signal }), []);
  const [variantId, setVariantId] = useState(''); const [registerId, setRegisterId] = useState(''); const [batchId, setBatchId] = useState(''); const [quantity, setQuantity] = useState(''); const [witness, setWitness] = useState(''); const [message, setMessage] = useState<string | null>(null); const [working, setWorking] = useState(false);
  async function open() { if (!variantId) return; setWorking(true); try { const result = await openControlledRegister(variantId, crypto.randomUUID()); setRegisterId(result.register_id); setMessage(`Register opened (${result.schedule}).`); } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not open register.'); } finally { setWorking(false); } }
  async function record() { if (!registerId || !batchId || !witness || !quantity) return; setWorking(true); try { const result = await recordControlledMovement(registerId, { batch_id: batchId, quantity_delta: Number(quantity), reason_code: 'dispensed', witness_profile_id: witness }, crypto.randomUUID()); setMessage(`Movement recorded; projected quantity ${result.projected_quantity}.`); } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not record movement.'); } finally { setWorking(false); } }
  if (authLoading || !user) return <div className="flex items-center justify-center min-h-screen"><div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-700" /></div>;
  const medications = data?.data ?? [];
  return <main className="flex-1 flex flex-col h-full overflow-hidden bg-slate-50"><TopBar breadcrumbs={[{ label: 'Pharmacy' }, { label: 'Controlled substances' }]} /><div className="flex-1 overflow-y-auto p-6"><div className="max-w-5xl mx-auto space-y-6"><header><h1 className="text-3xl font-bold">Controlled substance register</h1><p className="text-slate-500">Append-only witnessed movements. Recent step-up is required by the backend.</p></header><ResourceState isLoading={isLoading} error={error} isEmpty={medications.length === 0} onRetry={reload} loadingLabel="Loading medications..." errorTitle="Could not load controlled-substance setup" emptyTitle="No medication variants available" emptyBody="A medication variant is required to open a register." forbiddenTitle="You cannot manage controlled registers" emptyIcon="gavel" />{medications.length > 0 && <section className="bg-white rounded-xl border p-6 space-y-4"><label className="block text-sm font-medium">Medication variant<select value={variantId} onChange={(e) => setVariantId(e.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value="">Select a variant</option>{medications.map((m) => <option key={m.medication_id} value={m.medication_id}>{m.generic_name}</option>)}</select></label><button disabled={working || !variantId} onClick={open} className="px-4 py-2 rounded-lg bg-blue-700 text-white disabled:opacity-50">Open register</button>{registerId && <div className="border-t pt-4 space-y-3"><p className="text-sm text-slate-600">Register {registerId}</p><input value={batchId} onChange={(e) => setBatchId(e.target.value)} placeholder="Batch ID" className="w-full rounded-lg border p-2" /><input value={quantity} onChange={(e) => setQuantity(e.target.value)} type="number" placeholder="Quantity delta" className="w-full rounded-lg border p-2" /><input value={witness} onChange={(e) => setWitness(e.target.value)} placeholder="Witness profile ID" className="w-full rounded-lg border p-2" /><button disabled={working} onClick={record} className="px-4 py-2 rounded-lg bg-slate-900 text-white disabled:opacity-50">Record witnessed movement</button></div>}{message && <div role="status" className="rounded-lg bg-slate-100 p-3 text-sm">{message}</div>}</section>}</div></div></main>;
}
