import 'package:smartcura_contracts/smartcura_contracts.dart';

import '../network/api_error.dart';

/// Display-friendly models for the doctor AI assistant and artifacts surfaces.
///
/// The underlying wire types — [DoctorAiAssistantResponse], [AiArtifact] and
/// [AiArtifactList] — are generated by the contracts package and decoded by
/// [contract_decoders.dart]. This file holds the small presentation-only
/// helpers the screens need: a UI state envelope for the synchronous assistant
/// call and a helper that maps the generated [AiArtifactType] enum to a
/// human-readable label.

// ---------------------------------------------------------------------------
// Assistant call state (UI envelope)
// ---------------------------------------------------------------------------

/// UI state for a synchronous `POST /doctor/ai/assistant` call.
///
/// Mirrors the shape used by [RoomTokenNotifier] and [AiAssistantNotifier] but
/// is declared here so the assistant screen does not depend on a specific
/// provider class name. Carries the decoded response, an [ApiError] when the
/// call failed, and a `loading` flag.
class DoctorAiAssistantUiState {
  const DoctorAiAssistantUiState({
    this.response,
    this.error,
    this.loading = false,
    this.notConfigured = false,
    this.providerUnavailable = false,
  });

  final DoctorAiAssistantResponse? response;
  final ApiError? error;
  final bool loading;

  /// True when the backend answered 501 — the AI provider is not configured.
  /// Distinct from [error] because the remedy (contact an administrator) is
  /// not a retry.
  final bool notConfigured;

  /// True when the backend answered 503 — the provider is configured but
  /// currently unreachable. Also not retried blindly.
  final bool providerUnavailable;

  DoctorAiAssistantUiState copyWith({
    DoctorAiAssistantResponse? response,
    ApiError? error,
    bool? loading,
    bool? notConfigured,
    bool? providerUnavailable,
  }) =>
      DoctorAiAssistantUiState(
        response: response ?? this.response,
        error: error,
        loading: loading ?? this.loading,
        notConfigured: notConfigured ?? false,
        providerUnavailable: providerUnavailable ?? false,
      );
}

// ---------------------------------------------------------------------------
// Display helpers for artifact enums
// ---------------------------------------------------------------------------

/// Human-readable label for an [AiArtifactType], exhaustive over the generated
/// enum so a new wire value surfaces as `Unknown` instead of a wrong name.
String doctorAiArtifactTypeLabel(AiArtifactType type) => switch (type) {
      AiArtifactType.symptomSummary => 'Symptom summary',
      AiArtifactType.careNavigation => 'Care navigation',
      AiArtifactType.healthSummary => 'Health summary',
      AiArtifactType.dailySummary => 'Daily summary',
      AiArtifactType.trendAnalysis => 'Trend analysis',
      AiArtifactType.riskFlag => 'Risk flag',
      AiArtifactType.forecast => 'Forecast',
      AiArtifactType.anomaly => 'Anomaly',
      AiArtifactType.unknown => 'Unknown',
    };

/// Human-readable label for an [AiRiskLevel].
String doctorAiRiskLevelLabel(AiRiskLevel level) => switch (level) {
      AiRiskLevel.unknown => 'Unknown',
      AiRiskLevel.low => 'Low',
      AiRiskLevel.moderate => 'Moderate',
      AiRiskLevel.high => 'High',
      AiRiskLevel.critical => 'Critical',
    };

/// Human-readable label for an [AiReviewStatus].
String doctorAiReviewStatusLabel(AiReviewStatus status) => switch (status) {
      AiReviewStatus.pendingReview => 'Pending review',
      AiReviewStatus.approved => 'Approved',
      AiReviewStatus.rejected => 'Rejected',
      AiReviewStatus.superseded => 'Superseded',
      AiReviewStatus.unknown => 'Unknown',
    };
