'use client';

import { useState } from 'react';
import { useApiResource } from '@/hooks/use-api-resource';
import ResourceState from '@/components/data/ResourceState';
import { listEmergencyEvents, recordEmergencyCommunication } from '@/lib/api/emergency';

export default function EmergencyCommunicationsPage() {
  const {data,isLoading,error,reload}=useApiResource(signal=>listEmergencyEvents({activeOnly:true,limit:100,signal}),[]); const [eventId,setEventId]=useState(''); const [summary,setSummary]=useState(''); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState('');
  async function record(e:React.FormEvent){e.preventDefault();if(!eventId||!summary)return;setSaving(true);setNotice('');try{await recordEmergencyCommunication(eventId,{channel:'radio',direction:'outbound',summary_code:summary});setSummary('');setNotice('Communication recorded.');}catch{setNotice('Communication could not be recorded.')}finally{setSaving(false)}}
  return <main className="flex-1 overflow-y-auto p-8 bg-[#F9FAFB]"><div className="max-w-4xl mx-auto space-y-6"><div><h1 className="text-3xl font-bold text-slate-900">Emergency communications</h1><p className="text-slate-500 mt-1">Record structured dispatch communications against an emergency event.</p></div><ResourceState isLoading={isLoading} error={error} isEmpty={!data?.data.length} onRetry={reload} loadingLabel="Loading active emergencies…" forbiddenTitle="You cannot view emergency communications" errorTitle="Could not load emergencies" emptyTitle="No active emergencies" emptyBody="Raise or select an active emergency before recording communication." emptyIcon="forum"/>{data&&data.data.length>0&&<form onSubmit={record} className="bg-white rounded-xl border border-slate-200 p-6 space-y-4"><label className="block text-sm font-semibold">Emergency event<select required value={eventId} onChange={e=>setEventId(e.target.value)} className="mt-1 w-full rounded border px-3 py-2 font-normal"><option value="">Select event</option>{data.data.map(e=><option key={e.emergency_event_id} value={e.emergency_event_id}>{e.emergency_event_id.slice(0,8)} · {e.category_code} · {e.status}</option>)}</select></label><label className="block text-sm font-semibold">Summary code<input required pattern="[a-z][a-z0-9_]{1,62}" value={summary} onChange={e=>setSummary(e.target.value)} placeholder="unit_status_update" className="mt-1 w-full rounded border px-3 py-2 font-normal"/></label>{notice&&<p className="text-sm text-slate-700">{notice}</p>}<button disabled={saving} className="rounded bg-[#1e3fae] px-5 py-2.5 font-bold text-white disabled:opacity-50">{saving?'Recording…':'Record radio communication'}</button></form>}</div></main>;
}
