-- WP-04: profile detail, professional verification, private object metadata,
-- consent and care access.
--
-- Design rules this migration follows, all inherited from the existing
-- foundation rather than invented here:
--   * every identifier is a PostgreSQL 18 `uuidv7()` uuid generated by the
--     application inside the same transaction as the aggregate write;
--   * optimistic concurrency uses an integer `version` column with a `>= 0`
--     check, so a stale writer is rejected instead of silently overwriting;
--   * any foreign key that could cross an organization boundary is COMPOSITE
--     and includes `organization_id`, following the
--     `membership_sites_membership_org_fk` / `membership_sites_site_org_fk`
--     precedent from migration 0008. A single-column reference would let a row
--     in organization A point at a resource in organization B, which no
--     application-level guard can retroactively repair;
--   * `verification_status` is REUSED, not redefined. The membership-level
--     column already exists on `organization_memberships`; the per-document
--     column added here is a narrower instance of the same vocabulary;
--   * permissions are seeded per action. No `*` action is introduced, because
--     `permissionMatches` treats `*` as matching every present and future
--     action, and migrations 0009/0010 deliberately removed the last wildcard.
--
-- Preflight: this migration creates nine tables, ten enum types and several
-- composite foreign keys whose target unique indexes must already exist. It
-- also seeds `role_permissions` rows whose `role_id` foreign key can only be
-- satisfied by the roles seeded in 0004. Rather than letting any of that abort
-- with an opaque server error, assert every precondition first and report the
-- specific missing object, following the precedent in migration 0008.
DO $$
DECLARE
  server_version integer;
  missing_roles text;
  existing_tables text;
BEGIN
  -- PostgreSQL 18 is required: every primary key in this migration is written
  -- by the built-in `uuidv7()`, which does not exist before 18. Failing here is
  -- far cheaper than discovering it on the first INSERT.
  SELECT current_setting('server_version_num')::integer INTO server_version;
  IF server_version < 180000 THEN
    RAISE EXCEPTION
      'Migration 0011 aborted: PostgreSQL 18 or newer is required for built-in uuidv7(), found server_version_num=%.',
      server_version;
  END IF;

  -- The composite membership foreign keys below reference
  -- (membership_id, organization_id). PostgreSQL requires a unique index on
  -- exactly those columns; migration 0008 created it. If a hand-edited database
  -- lost it, ADD CONSTRAINT would fail with a generic "no unique constraint
  -- matching given keys" message that hides which index is missing.
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public'
      AND indexname = 'organization_memberships_id_org_uq'
  ) THEN
    RAISE EXCEPTION
      'Migration 0011 aborted: unique index organization_memberships_id_org_uq is missing. Migration 0008 must be applied before this migration.';
  END IF;

  -- The role_permissions seed at the end of this migration has a foreign key to
  -- roles. A partially seeded roles table would abort the migration after the
  -- DDL has already run, so check the full system role set up front.
  SELECT COALESCE(string_agg(expected.role_id, ', ' ORDER BY expected.role_id), '')
  INTO missing_roles
  FROM (VALUES
    ('patient'), ('doctor'), ('driver'), ('pharmacy'),
    ('emergency'), ('admin'), ('super_admin')
  ) AS expected(role_id)
  WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE roles.role_id = expected.role_id
  );

  IF missing_roles <> '' THEN
    RAISE EXCEPTION
      'Migration 0011 aborted: required system role(s) missing from roles: %. Migration 0004 must be applied before this migration.',
      missing_roles;
  END IF;

  -- Guard against a partially applied earlier attempt. CREATE TABLE without
  -- IF NOT EXISTS is intentional (silently skipping a table would leave the
  -- schema out of step with the drizzle snapshot), so report every conflicting
  -- relation at once instead of stopping at the first one.
  SELECT COALESCE(string_agg(candidate.table_name, ', ' ORDER BY candidate.table_name), '')
  INTO existing_tables
  FROM (VALUES
    ('profile_addresses'), ('profile_emergency_contacts'), ('profile_allergies'),
    ('profile_conditions'), ('doctor_details'), ('doctor_specialties'),
    ('doctor_languages'), ('stored_objects'), ('verification_documents'),
    ('consent_grants'), ('care_assignments')
  ) AS candidate(table_name)
  WHERE to_regclass('public.' || candidate.table_name) IS NOT NULL;

  IF existing_tables <> '' THEN
    RAISE EXCEPTION
      'Migration 0011 aborted: table(s) already exist from a partially applied attempt: %. Drop them deliberately or repair the drizzle journal before retrying.',
      existing_tables;
  END IF;
END;
$$;--> statement-breakpoint
CREATE TYPE "public"."address_kind" AS ENUM('home', 'work', 'billing', 'delivery', 'other');--> statement-breakpoint
CREATE TYPE "public"."allergy_severity" AS ENUM('mild', 'moderate', 'severe', 'life_threatening');--> statement-breakpoint
CREATE TYPE "public"."care_assignment_status" AS ENUM('active', 'completed', 'revoked', 'expired');--> statement-breakpoint
CREATE TYPE "public"."clinical_record_status" AS ENUM('active', 'inactive', 'resolved', 'entered_in_error');--> statement-breakpoint
CREATE TYPE "public"."condition_severity" AS ENUM('mild', 'moderate', 'severe', 'critical');--> statement-breakpoint
CREATE TYPE "public"."consent_revocation_reason" AS ENUM('grantor_request', 'grantee_request', 'admin_action', 'superseded', 'policy_violation', 'membership_ended');--> statement-breakpoint
CREATE TYPE "public"."consent_scope" AS ENUM('profile_contact', 'clinical_record', 'medication', 'iot_reading', 'ai_artifact', 'full_record');--> statement-breakpoint
CREATE TYPE "public"."malware_scan_state" AS ENUM('not_scanned', 'scanning', 'clean', 'infected', 'scan_failed');--> statement-breakpoint
CREATE TYPE "public"."stored_object_status" AS ENUM('pending', 'finalized', 'quarantined', 'deleted');--> statement-breakpoint
CREATE TYPE "public"."verification_document_kind" AS ENUM('medical_license', 'national_id', 'driving_licence', 'vehicle_registration', 'pharmacy_licence', 'qualification_certificate', 'professional_indemnity');--> statement-breakpoint
-- Time-bounded clinician-to-patient care relationship. `policy-matrix.md` makes
-- an active assignment (not organization membership) the object-relationship
-- test for ordinary clinical access, so this table is authorization input and
-- must never be mutated in place to "fix" history: it is closed with
-- `ended_at` and a reason instead.
CREATE TABLE "care_assignments" (
	"assignment_id" uuid PRIMARY KEY NOT NULL,
	"organization_id" uuid NOT NULL,
	"clinician_membership_id" uuid NOT NULL,
	"patient_profile_id" uuid NOT NULL,
	"status" "care_assignment_status" DEFAULT 'active' NOT NULL,
	"assigned_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ended_at" timestamp with time zone,
	"ended_reason" varchar(64),
	"assigned_by_membership_id" uuid,
	"version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "care_assignments_version_check" CHECK ("care_assignments"."version" >= 0),
	-- An assignment cannot end before it began; a clock skew or a bad manual
	-- correction would otherwise create a negative-duration care window that
	-- reads as "valid at time T" for arbitrary T.
	CONSTRAINT "care_assignments_ended_order_check" CHECK ("care_assignments"."ended_at" IS NULL OR "care_assignments"."ended_at" >= "care_assignments"."assigned_at"),
	-- `status = 'active'` and `ended_at IS NULL` are the same fact expressed two
	-- ways. Binding them with an equivalence removes the "revoked but still
	-- open" and "ended but still active" rows that would make an authorization
	-- query answer differently depending on which column it trusted.
	CONSTRAINT "care_assignments_lifecycle_check" CHECK (("care_assignments"."status" = 'active') = ("care_assignments"."ended_at" IS NULL)),
	CONSTRAINT "care_assignments_ended_reason_check" CHECK ("care_assignments"."ended_reason" IS NULL OR "care_assignments"."ended_at" IS NOT NULL)
);
--> statement-breakpoint
-- Explicit patient consent. The grantee is either another profile (a guardian
-- or dependant arrangement) or an organization membership (a clinician or staff
-- member). Expiry and revocation are separate facts: an expired grant lapsed on
-- its own, a revoked grant was withdrawn by someone and therefore carries a
-- reason code and participates in audit.
CREATE TABLE "consent_grants" (
	"consent_id" uuid PRIMARY KEY NOT NULL,
	"organization_id" uuid NOT NULL,
	"grantor_profile_id" uuid NOT NULL,
	"grantee_profile_id" uuid,
	"grantee_membership_id" uuid,
	"scope" "consent_scope" NOT NULL,
	"purpose" varchar(160) NOT NULL,
	"granted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"revocation_reason" "consent_revocation_reason",
	"version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "consent_grants_version_check" CHECK ("consent_grants"."version" >= 0),
	-- Exactly one grantee. Both columns set would make "who may act on this
	-- grant" ambiguous; neither set would create a grant that authorises nobody
	-- yet still appears in a consent list.
	CONSTRAINT "consent_grants_grantee_exclusive_check" CHECK (("consent_grants"."grantee_profile_id" IS NOT NULL) <> ("consent_grants"."grantee_membership_id" IS NOT NULL)),
	-- A profile cannot consent to itself. `own` access is a property of
	-- ownership, never of consent, and a self-grant would let a revocation of
	-- consent be misread as a removal of the owner's own access.
	CONSTRAINT "consent_grants_self_grant_check" CHECK ("consent_grants"."grantee_profile_id" IS NULL OR "consent_grants"."grantee_profile_id" <> "consent_grants"."grantor_profile_id"),
	CONSTRAINT "consent_grants_expiry_order_check" CHECK ("consent_grants"."expires_at" IS NULL OR "consent_grants"."expires_at" > "consent_grants"."granted_at"),
	CONSTRAINT "consent_grants_revocation_order_check" CHECK ("consent_grants"."revoked_at" IS NULL OR "consent_grants"."revoked_at" >= "consent_grants"."granted_at"),
	-- A revocation without a reason code cannot be reviewed, and a reason code
	-- without a revocation timestamp implies a revocation that never happened.
	CONSTRAINT "consent_grants_revocation_reason_check" CHECK (("consent_grants"."revoked_at" IS NULL) = ("consent_grants"."revocation_reason" IS NULL))
);
--> statement-breakpoint
-- Professional detail for a doctor MEMBERSHIP, not a profile. One profile may
-- hold several memberships (different organizations, or doctor plus patient),
-- and a fee, biography and registration number belong to the organization the
-- doctor practises in. Keying on `membership_id` makes that one-to-one by
-- construction instead of by application convention.
CREATE TABLE "doctor_details" (
	"membership_id" uuid PRIMARY KEY NOT NULL,
	"organization_id" uuid NOT NULL,
	"biography" text,
	"registration_number" varchar(64),
	"years_of_experience" integer DEFAULT 0 NOT NULL,
	"consultation_fee_sen" integer DEFAULT 0 NOT NULL,
	"currency" varchar(3) DEFAULT 'MYR' NOT NULL,
	"accepting_new_patients" boolean DEFAULT true NOT NULL,
	"version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "doctor_details_version_check" CHECK ("doctor_details"."version" >= 0),
	CONSTRAINT "doctor_details_experience_check" CHECK ("doctor_details"."years_of_experience" >= 0 AND "doctor_details"."years_of_experience" <= 80),
	-- Money is integer MYR sen, never floating point ringgit. A negative
	-- consultation fee is not a discount, it is a payout, and the payment
	-- aggregate has no representation for that.
	CONSTRAINT "doctor_details_fee_check" CHECK ("doctor_details"."consultation_fee_sen" >= 0),
	-- Single-currency by decision, not by omission. Multi-currency pricing needs
	-- a reviewed FX and settlement design, so the constraint fails loudly rather
	-- than letting an unpriceable row through.
	CONSTRAINT "doctor_details_currency_check" CHECK ("doctor_details"."currency" = 'MYR')
);
--> statement-breakpoint
-- Languages are a normalized child table rather than a text[] column so that
-- discovery can index and join on them, and so a typo is a constraint violation
-- instead of a silently unmatchable array element.
CREATE TABLE "doctor_languages" (
	"membership_id" uuid NOT NULL,
	"organization_id" uuid NOT NULL,
	"language_code" varchar(35) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "doctor_languages_pk" PRIMARY KEY("membership_id","language_code"),
	-- BCP 47 shape, matching `profiles.preferred_locale` conventions.
	CONSTRAINT "doctor_languages_code_check" CHECK ("doctor_languages"."language_code" ~ '^[a-z]{2,3}(-[A-Za-z0-9]{2,8})*$')
);
--> statement-breakpoint
-- Specialties are normalized for the same reason as languages, plus one extra:
-- doctor discovery filters and sorts on specialty, which an array column cannot
-- support with a plain btree index.
CREATE TABLE "doctor_specialties" (
	"membership_id" uuid NOT NULL,
	"organization_id" uuid NOT NULL,
	"specialty_code" varchar(64) NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "doctor_specialties_pk" PRIMARY KEY("membership_id","specialty_code"),
	-- Codes are canonical lowercase snake_case identifiers, never display text.
	-- Labels and localization are client concerns per the enum catalogue.
	CONSTRAINT "doctor_specialties_code_check" CHECK ("doctor_specialties"."specialty_code" ~ '^[a-z][a-z0-9_]{1,62}$')
);
--> statement-breakpoint
-- Addresses are owned by the profile and soft-deleted with `archived_at`, not
-- removed: an address that appeared on a past delivery or emergency dispatch is
-- evidence and must remain resolvable after the patient replaces it.
CREATE TABLE "profile_addresses" (
	"address_id" uuid PRIMARY KEY NOT NULL,
	"profile_id" uuid NOT NULL,
	"kind" "address_kind" DEFAULT 'home' NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"label" varchar(80),
	"line1" varchar(160) NOT NULL,
	"line2" varchar(160),
	"city" varchar(120) NOT NULL,
	"state" varchar(120) NOT NULL,
	"postcode" varchar(16) NOT NULL,
	"country_code" varchar(2) DEFAULT 'MY' NOT NULL,
	"archived_at" timestamp with time zone,
	"version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "profile_addresses_version_check" CHECK ("profile_addresses"."version" >= 0),
	-- ISO 3166-1 alpha-2, uppercase. Storing 'my' and 'MY' as different values
	-- would split the same country across two buckets.
	CONSTRAINT "profile_addresses_country_code_check" CHECK ("profile_addresses"."country_code" ~ '^[A-Z]{2}$'),
	CONSTRAINT "profile_addresses_postcode_check" CHECK ("profile_addresses"."postcode" ~ '^[A-Za-z0-9][A-Za-z0-9 -]{1,15}$'),
	-- An archived address must not remain the designated primary, otherwise the
	-- partial unique index below would hold a slot that no live row can claim.
	CONSTRAINT "profile_addresses_archived_primary_check" CHECK ("profile_addresses"."archived_at" IS NULL OR "profile_addresses"."is_primary" = false)
);
--> statement-breakpoint
-- Allergy list entries owned by the profile. `recorded_by_membership_id` is the
-- optional clinician attribution: a patient-entered allergy has no clinician,
-- and that difference is clinically meaningful, so the columns are nullable
-- rather than backfilled with a placeholder.
CREATE TABLE "profile_allergies" (
	"allergy_id" uuid PRIMARY KEY NOT NULL,
	"profile_id" uuid NOT NULL,
	"substance" varchar(160) NOT NULL,
	"reaction" varchar(240),
	"severity" "allergy_severity" NOT NULL,
	"status" "clinical_record_status" DEFAULT 'active' NOT NULL,
	"note" text,
	"recorded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"recorded_by_membership_id" uuid,
	"recorded_by_organization_id" uuid,
	"version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "profile_allergies_version_check" CHECK ("profile_allergies"."version" >= 0),
	-- Attribution is all-or-nothing: the composite foreign key needs both
	-- columns, and a membership without its organization cannot be checked
	-- against the organization boundary at all.
	CONSTRAINT "profile_allergies_recorder_pair_check" CHECK (("profile_allergies"."recorded_by_membership_id" IS NULL) = ("profile_allergies"."recorded_by_organization_id" IS NULL))
);
--> statement-breakpoint
-- Condition list entries owned by the profile. `entered_in_error` exists in
-- `clinical_record_status` precisely so that a mistaken entry is retired rather
-- than deleted; deleting it would erase the fact that a clinician once saw it.
CREATE TABLE "profile_conditions" (
	"condition_id" uuid PRIMARY KEY NOT NULL,
	"profile_id" uuid NOT NULL,
	"name" varchar(200) NOT NULL,
	"code_system" varchar(32),
	"code" varchar(32),
	"severity" "condition_severity",
	"status" "clinical_record_status" DEFAULT 'active' NOT NULL,
	"onset_on" date,
	"resolved_on" date,
	"note" text,
	"recorded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"recorded_by_membership_id" uuid,
	"recorded_by_organization_id" uuid,
	"version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "profile_conditions_version_check" CHECK ("profile_conditions"."version" >= 0),
	CONSTRAINT "profile_conditions_recorder_pair_check" CHECK (("profile_conditions"."recorded_by_membership_id" IS NULL) = ("profile_conditions"."recorded_by_organization_id" IS NULL)),
	-- A code is meaningless without the system that defines it, and a system
	-- without a code identifies nothing. Both or neither.
	CONSTRAINT "profile_conditions_code_pair_check" CHECK (("profile_conditions"."code_system" IS NULL) = ("profile_conditions"."code" IS NULL)),
	-- `resolved` and a resolution date are the same fact. Keeping them in step
	-- stops "resolved with no date" and "dated but still active" rows.
	CONSTRAINT "profile_conditions_resolved_status_check" CHECK (("profile_conditions"."status" = 'resolved') = ("profile_conditions"."resolved_on" IS NOT NULL)),
	CONSTRAINT "profile_conditions_resolved_order_check" CHECK ("profile_conditions"."resolved_on" IS NULL OR "profile_conditions"."onset_on" IS NULL OR "profile_conditions"."resolved_on" >= "profile_conditions"."onset_on")
);
--> statement-breakpoint
-- Ordered emergency contacts. Priority is the notification order used by the
-- SOS workflow, so it is an explicit integer rather than an implicit row order.
CREATE TABLE "profile_emergency_contacts" (
	"contact_id" uuid PRIMARY KEY NOT NULL,
	"profile_id" uuid NOT NULL,
	"full_name" varchar(120) NOT NULL,
	"relationship" varchar(64) NOT NULL,
	"phone_e164" varchar(16) NOT NULL,
	"email" varchar(320),
	"priority" integer DEFAULT 1 NOT NULL,
	"notify_on_emergency" boolean DEFAULT true NOT NULL,
	"archived_at" timestamp with time zone,
	"version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "profile_emergency_contacts_version_check" CHECK ("profile_emergency_contacts"."version" >= 0),
	-- Capped at five live contacts, matching the client contract. Enforcing the
	-- ceiling through the priority range keeps the limit in the database instead
	-- of only in the form that happens to be submitting.
	CONSTRAINT "profile_emergency_contacts_priority_check" CHECK ("profile_emergency_contacts"."priority" >= 1 AND "profile_emergency_contacts"."priority" <= 5),
	-- Same E.164 pattern as `profiles.phone_e164`, but NOT NULL here: an
	-- emergency contact that cannot be dialled is not a contact. An SOS
	-- workflow discovering an unusable number at dispatch time is a safety
	-- failure, so the number is validated at write time.
	CONSTRAINT "profile_emergency_contacts_phone_e164_check" CHECK ("profile_emergency_contacts"."phone_e164" ~ '^\+[1-9][0-9]{7,14}$'),
	CONSTRAINT "profile_emergency_contacts_email_check" CHECK ("profile_emergency_contacts"."email" IS NULL OR "profile_emergency_contacts"."email" ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$')
);
--> statement-breakpoint
-- Authoritative metadata for every private file. The bytes live in object
-- storage; this row is the only thing the platform trusts about them.
--
-- CRITICAL INVARIANT: a file that is not finalized, or whose malware scan is
-- not clean, must never be downloadable. That is encoded structurally by the
-- `downloadable` flag plus `stored_objects_downloadable_check`: the flag may be
-- true only when the upload is finalized, the scan is clean and the verified
-- digest matches the digest the client declared. Every download path reads the
-- flag, so an in-progress, quarantined, infected, unscanned or tampered object
-- cannot be served even if application code forgets a predicate. The flag is a
-- plain column rather than a generated column so the check remains provably
-- immutable across PostgreSQL versions, and the constraint is one-directional
-- on purpose: the database refuses to CALL something downloadable, and never
-- promotes an object to downloadable on its own.
CREATE TABLE "stored_objects" (
	"object_id" uuid PRIMARY KEY NOT NULL,
	"organization_id" uuid NOT NULL,
	"storage_provider" varchar(32) NOT NULL,
	"bucket" varchar(128) NOT NULL,
	"object_key" varchar(512) NOT NULL,
	"media_type" varchar(160) NOT NULL,
	"byte_size" bigint NOT NULL,
	"declared_sha256" varchar(64) NOT NULL,
	"verified_sha256" varchar(64),
	"upload_status" "stored_object_status" DEFAULT 'pending' NOT NULL,
	"scan_state" "malware_scan_state" DEFAULT 'not_scanned' NOT NULL,
	"downloadable" boolean DEFAULT false NOT NULL,
	"scanned_at" timestamp with time zone,
	"finalized_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	"uploaded_by_profile_id" uuid NOT NULL,
	"version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "stored_objects_version_check" CHECK ("stored_objects"."version" >= 0),
	-- A zero-byte private file is always a failed or truncated upload. Rejecting
	-- it here keeps the "finalized" state honest.
	CONSTRAINT "stored_objects_byte_size_check" CHECK ("stored_objects"."byte_size" > 0),
	-- 64 lowercase hex characters. Mixed case would make two spellings of the
	-- same digest compare unequal, which silently breaks integrity comparison.
	CONSTRAINT "stored_objects_declared_sha256_check" CHECK ("stored_objects"."declared_sha256" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "stored_objects_verified_sha256_check" CHECK ("stored_objects"."verified_sha256" IS NULL OR "stored_objects"."verified_sha256" ~ '^[0-9a-f]{64}$'),
	-- The download invariant. A mismatch between declared and verified digest is
	-- deliberately storable (forensics need the evidence) but can never be
	-- downloadable.
	CONSTRAINT "stored_objects_downloadable_check" CHECK ("stored_objects"."downloadable" = false OR ("stored_objects"."upload_status" = 'finalized' AND "stored_objects"."scan_state" = 'clean' AND "stored_objects"."verified_sha256" IS NOT NULL AND "stored_objects"."verified_sha256" = "stored_objects"."declared_sha256")),
	-- Finalization means the server has seen the bytes and hashed them itself.
	-- Without a verified digest, "finalized" would only mean "the client said so".
	CONSTRAINT "stored_objects_finalized_checksum_check" CHECK ("stored_objects"."upload_status" <> 'finalized' OR ("stored_objects"."finalized_at" IS NOT NULL AND "stored_objects"."verified_sha256" IS NOT NULL)),
	CONSTRAINT "stored_objects_pending_finalized_at_check" CHECK ("stored_objects"."finalized_at" IS NULL OR "stored_objects"."upload_status" <> 'pending'),
	-- A terminal scan verdict must carry the time it was reached, and a
	-- not-yet-scanned object must not carry one. Otherwise scan freshness
	-- policies cannot distinguish "never scanned" from "scanned long ago".
	CONSTRAINT "stored_objects_scanned_at_check" CHECK (("stored_objects"."scan_state" IN ('not_scanned', 'scanning')) = ("stored_objects"."scanned_at" IS NULL)),
	CONSTRAINT "stored_objects_deleted_at_check" CHECK (("stored_objects"."upload_status" = 'deleted') = ("stored_objects"."deleted_at" IS NOT NULL))
);
--> statement-breakpoint
-- A verification document belongs to an organization_membership, so the same
-- human can be a verified doctor in one organization and an unverified
-- applicant in another. `status` reuses the existing `verification_status` enum:
-- a document is reviewed with the same vocabulary as the membership it supports,
-- which is what lets the membership-level status be derived from its documents
-- instead of drifting from them.
CREATE TABLE "verification_documents" (
	"document_id" uuid PRIMARY KEY NOT NULL,
	"membership_id" uuid NOT NULL,
	"organization_id" uuid NOT NULL,
	"object_id" uuid NOT NULL,
	"document_kind" "verification_document_kind" NOT NULL,
	"status" "verification_status" DEFAULT 'pending_review' NOT NULL,
	"issuing_authority" varchar(160),
	"issued_at" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"submitted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"reviewed_by_membership_id" uuid,
	"reviewed_at" timestamp with time zone,
	"review_decision_reason" varchar(128),
	"review_note" text,
	"version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "verification_documents_version_check" CHECK ("verification_documents"."version" >= 0),
	CONSTRAINT "verification_documents_validity_order_check" CHECK ("verification_documents"."issued_at" IS NULL OR "verification_documents"."expires_at" IS NULL OR "verification_documents"."expires_at" > "verification_documents"."issued_at"),
	-- A decision needs a decider. Recording one without the other produces an
	-- unauditable approval, which is the exact failure verification exists to
	-- prevent.
	CONSTRAINT "verification_documents_review_pair_check" CHECK (("verification_documents"."reviewed_at" IS NULL) = ("verification_documents"."reviewed_by_membership_id" IS NULL)),
	-- Reviewed documents may only rest in a reviewed state. `not_submitted` and
	-- `pending_review` describe a document nobody has decided on yet.
	CONSTRAINT "verification_documents_review_status_check" CHECK ("verification_documents"."reviewed_at" IS NULL OR "verification_documents"."status" IN ('changes_requested', 'approved', 'rejected', 'suspended')),
	CONSTRAINT "verification_documents_decision_reason_check" CHECK ("verification_documents"."review_decision_reason" IS NULL OR "verification_documents"."reviewed_at" IS NOT NULL),
	-- A negative outcome must state why, because the applicant is told why and a
	-- reviewer decision without a reason code cannot be appealed or reviewed.
	CONSTRAINT "verification_documents_rejection_reason_check" CHECK ("verification_documents"."status" NOT IN ('changes_requested', 'rejected') OR "verification_documents"."review_decision_reason" IS NOT NULL)
);
--> statement-breakpoint
-- These two unique indexes are created BEFORE the composite foreign keys that
-- reference them. PostgreSQL requires a unique index on exactly the referenced
-- column list, and the default generated ordering would emit the ADD CONSTRAINT
-- first and fail. Same reason migration 0008 created its unique indexes ahead of
-- the membership_sites composite keys.
CREATE UNIQUE INDEX "stored_objects_id_organization_uq" ON "stored_objects" USING btree ("object_id","organization_id");--> statement-breakpoint
CREATE UNIQUE INDEX "doctor_details_membership_org_uq" ON "doctor_details" USING btree ("membership_id","organization_id");--> statement-breakpoint
ALTER TABLE "care_assignments" ADD CONSTRAINT "care_assignments_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- `patient_profile_id` is a plain reference on purpose: profiles are platform
-- level, not organization owned, so there is no organization boundary to cross.
-- The organization is carried by the assignment row itself and by the clinician
-- membership below.
ALTER TABLE "care_assignments" ADD CONSTRAINT "care_assignments_patient_profile_id_profiles_profile_id_fk" FOREIGN KEY ("patient_profile_id") REFERENCES "public"."profiles"("profile_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- Composite: the clinician must be a member of the SAME organization the
-- assignment was made in. A single-column membership reference would allow an
-- organization A assignment to name an organization B clinician, and that
-- clinician would then pass the `assigned` object-relationship test for a
-- patient their organization never treated.
ALTER TABLE "care_assignments" ADD CONSTRAINT "care_assignments_clinician_org_fk" FOREIGN KEY ("clinician_membership_id","organization_id") REFERENCES "public"."organization_memberships"("membership_id","organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- Composite: the administrator who created the assignment must also belong to
-- the organization, so the accountability trail cannot point outside it.
ALTER TABLE "care_assignments" ADD CONSTRAINT "care_assignments_assigner_org_fk" FOREIGN KEY ("assigned_by_membership_id","organization_id") REFERENCES "public"."organization_memberships"("membership_id","organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consent_grants" ADD CONSTRAINT "consent_grants_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consent_grants" ADD CONSTRAINT "consent_grants_grantor_profile_id_profiles_profile_id_fk" FOREIGN KEY ("grantor_profile_id") REFERENCES "public"."profiles"("profile_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consent_grants" ADD CONSTRAINT "consent_grants_grantee_profile_id_profiles_profile_id_fk" FOREIGN KEY ("grantee_profile_id") REFERENCES "public"."profiles"("profile_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- Composite: a consent recorded in organization A cannot name a membership in
-- organization B. Without the organization column in the key, a revoked or
-- foreign membership could still satisfy a consent lookup.
ALTER TABLE "consent_grants" ADD CONSTRAINT "consent_grants_grantee_membership_org_fk" FOREIGN KEY ("grantee_membership_id","organization_id") REFERENCES "public"."organization_memberships"("membership_id","organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- Composite: doctor detail rows are pinned to the organization of the
-- membership they describe, so a fee or biography can never be attached across
-- an organization boundary.
ALTER TABLE "doctor_details" ADD CONSTRAINT "doctor_details_membership_org_fk" FOREIGN KEY ("membership_id","organization_id") REFERENCES "public"."organization_memberships"("membership_id","organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- Child rows reference doctor_details composite rather than
-- organization_memberships, which both pins the organization and guarantees a
-- language or specialty cannot exist without the doctor row it describes.
ALTER TABLE "doctor_languages" ADD CONSTRAINT "doctor_languages_doctor_org_fk" FOREIGN KEY ("membership_id","organization_id") REFERENCES "public"."doctor_details"("membership_id","organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "doctor_specialties" ADD CONSTRAINT "doctor_specialties_doctor_org_fk" FOREIGN KEY ("membership_id","organization_id") REFERENCES "public"."doctor_details"("membership_id","organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profile_addresses" ADD CONSTRAINT "profile_addresses_profile_id_profiles_profile_id_fk" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("profile_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profile_allergies" ADD CONSTRAINT "profile_allergies_profile_id_profiles_profile_id_fk" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("profile_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- Composite: clinician attribution on a clinical entry names a membership plus
-- its organization, so "recorded by Dr X of organization A" cannot silently
-- become "recorded by Dr X of organization B" and grant the wrong organization
-- provenance over a patient's record.
ALTER TABLE "profile_allergies" ADD CONSTRAINT "profile_allergies_recorder_org_fk" FOREIGN KEY ("recorded_by_membership_id","recorded_by_organization_id") REFERENCES "public"."organization_memberships"("membership_id","organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profile_conditions" ADD CONSTRAINT "profile_conditions_profile_id_profiles_profile_id_fk" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("profile_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profile_conditions" ADD CONSTRAINT "profile_conditions_recorder_org_fk" FOREIGN KEY ("recorded_by_membership_id","recorded_by_organization_id") REFERENCES "public"."organization_memberships"("membership_id","organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profile_emergency_contacts" ADD CONSTRAINT "profile_emergency_contacts_profile_id_profiles_profile_id_fk" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("profile_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stored_objects" ADD CONSTRAINT "stored_objects_organization_id_organizations_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stored_objects" ADD CONSTRAINT "stored_objects_uploaded_by_profile_id_profiles_profile_id_fk" FOREIGN KEY ("uploaded_by_profile_id") REFERENCES "public"."profiles"("profile_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- Composite: the document belongs to a membership IN the stated organization.
ALTER TABLE "verification_documents" ADD CONSTRAINT "verification_documents_membership_org_fk" FOREIGN KEY ("membership_id","organization_id") REFERENCES "public"."organization_memberships"("membership_id","organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- Composite: the reviewer must be a membership in the same organization. A
-- reviewer from another organization approving a licence would be an
-- authorization escalation that no route guard can undo after the fact.
ALTER TABLE "verification_documents" ADD CONSTRAINT "verification_documents_reviewer_org_fk" FOREIGN KEY ("reviewed_by_membership_id","organization_id") REFERENCES "public"."organization_memberships"("membership_id","organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- Composite: the stored object backing the document must live in the same
-- organization. This is the constraint that stops organization A from pointing
-- a verification document at organization B's private file and then reading it
-- through the document's own access policy.
ALTER TABLE "verification_documents" ADD CONSTRAINT "verification_documents_object_org_fk" FOREIGN KEY ("object_id","organization_id") REFERENCES "public"."stored_objects"("object_id","organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- One live care relationship per clinician/patient pair. Duplicate active rows
-- would make revocation ambiguous: closing one would leave access open through
-- the other.
CREATE UNIQUE INDEX "care_assignments_active_uq" ON "care_assignments" USING btree ("clinician_membership_id","patient_profile_id") WHERE status = 'active';--> statement-breakpoint
CREATE INDEX "care_assignments_patient_status_idx" ON "care_assignments" USING btree ("patient_profile_id","status");--> statement-breakpoint
CREATE INDEX "care_assignments_clinician_status_idx" ON "care_assignments" USING btree ("clinician_membership_id","status");--> statement-breakpoint
CREATE INDEX "care_assignments_org_assigned_idx" ON "care_assignments" USING btree ("organization_id","assigned_at","assignment_id");--> statement-breakpoint
CREATE INDEX "consent_grants_grantor_scope_idx" ON "consent_grants" USING btree ("grantor_profile_id","scope","revoked_at");--> statement-breakpoint
CREATE INDEX "consent_grants_grantee_membership_idx" ON "consent_grants" USING btree ("grantee_membership_id","revoked_at");--> statement-breakpoint
CREATE INDEX "consent_grants_grantee_profile_idx" ON "consent_grants" USING btree ("grantee_profile_id","revoked_at");--> statement-breakpoint
CREATE INDEX "consent_grants_expiry_idx" ON "consent_grants" USING btree ("expires_at");--> statement-breakpoint
-- Two partial unique indexes instead of one over a nullable grantee pair.
-- A single index would compare NULLs as distinct and therefore permit unlimited
-- duplicate active grants; splitting by grantee kind avoids NULL semantics
-- entirely and keeps "one active grant per grantor, grantee, scope and purpose"
-- actually enforced.
CREATE UNIQUE INDEX "consent_grants_active_profile_grantee_uq" ON "consent_grants" USING btree ("grantor_profile_id","grantee_profile_id","scope","purpose") WHERE revoked_at IS NULL AND grantee_profile_id IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "consent_grants_active_membership_grantee_uq" ON "consent_grants" USING btree ("grantor_profile_id","grantee_membership_id","scope","purpose") WHERE revoked_at IS NULL AND grantee_membership_id IS NOT NULL;--> statement-breakpoint
-- A professional registration number is unique within an organization. Partial
-- so that doctors who have not supplied one yet do not collide on NULL.
CREATE UNIQUE INDEX "doctor_details_registration_number_uq" ON "doctor_details" USING btree ("organization_id","registration_number") WHERE registration_number IS NOT NULL;--> statement-breakpoint
CREATE INDEX "doctor_details_org_fee_idx" ON "doctor_details" USING btree ("organization_id","consultation_fee_sen");--> statement-breakpoint
CREATE INDEX "doctor_languages_code_idx" ON "doctor_languages" USING btree ("language_code","organization_id");--> statement-breakpoint
CREATE INDEX "doctor_specialties_code_idx" ON "doctor_specialties" USING btree ("specialty_code","organization_id");--> statement-breakpoint
-- At most one primary specialty per doctor, so discovery has a deterministic
-- headline specialty rather than picking whichever row sorts first.
CREATE UNIQUE INDEX "doctor_specialties_primary_uq" ON "doctor_specialties" USING btree ("membership_id") WHERE is_primary;--> statement-breakpoint
CREATE INDEX "profile_addresses_profile_idx" ON "profile_addresses" USING btree ("profile_id","is_primary");--> statement-breakpoint
-- Exactly one designated primary address per profile among live rows. Archived
-- rows are excluded so history does not block a replacement.
CREATE UNIQUE INDEX "profile_addresses_primary_uq" ON "profile_addresses" USING btree ("profile_id") WHERE is_primary AND archived_at IS NULL;--> statement-breakpoint
CREATE INDEX "profile_allergies_profile_status_idx" ON "profile_allergies" USING btree ("profile_id","status");--> statement-breakpoint
CREATE INDEX "profile_allergies_recorder_idx" ON "profile_allergies" USING btree ("recorded_by_membership_id");--> statement-breakpoint
-- No duplicate ACTIVE entry for the same substance. Retired and
-- entered-in-error rows are intentionally exempt: clinical history is allowed
-- to contain the same substance more than once over time.
CREATE UNIQUE INDEX "profile_allergies_active_substance_uq" ON "profile_allergies" USING btree ("profile_id","substance") WHERE status = 'active';--> statement-breakpoint
CREATE INDEX "profile_conditions_profile_status_idx" ON "profile_conditions" USING btree ("profile_id","status");--> statement-breakpoint
CREATE INDEX "profile_conditions_recorder_idx" ON "profile_conditions" USING btree ("recorded_by_membership_id");--> statement-breakpoint
CREATE UNIQUE INDEX "profile_conditions_active_name_uq" ON "profile_conditions" USING btree ("profile_id","name") WHERE status = 'active';--> statement-breakpoint
CREATE INDEX "profile_emergency_contacts_profile_idx" ON "profile_emergency_contacts" USING btree ("profile_id","priority");--> statement-breakpoint
-- Priority is a strict order, not a preference: two live contacts sharing
-- priority 1 would make SOS notification order non-deterministic.
CREATE UNIQUE INDEX "profile_emergency_contacts_priority_uq" ON "profile_emergency_contacts" USING btree ("profile_id","priority") WHERE archived_at IS NULL;--> statement-breakpoint
-- One metadata row per physical object. Two rows describing the same key could
-- disagree about scan state, and the download path would then depend on which
-- row was read.
CREATE UNIQUE INDEX "stored_objects_location_uq" ON "stored_objects" USING btree ("storage_provider","bucket","object_key");--> statement-breakpoint
CREATE INDEX "stored_objects_scan_queue_idx" ON "stored_objects" USING btree ("scan_state","upload_status","created_at");--> statement-breakpoint
CREATE INDEX "stored_objects_uploader_idx" ON "stored_objects" USING btree ("uploaded_by_profile_id","created_at");--> statement-breakpoint
-- A stored object backs at most one verification document, so revoking a
-- document cannot leave a second document holding a signed URL to the same file.
CREATE UNIQUE INDEX "verification_documents_object_uq" ON "verification_documents" USING btree ("object_id");--> statement-breakpoint
-- One IN-FLIGHT or CURRENT document per membership per kind. A membership can
-- still hold many documents of DIFFERENT kinds, and many superseded documents
-- of the same kind, because rejected, expired and suspended rows fall outside
-- the predicate and remain as history.
CREATE UNIQUE INDEX "verification_documents_membership_kind_current_uq" ON "verification_documents" USING btree ("membership_id","document_kind") WHERE status IN ('pending_review', 'changes_requested', 'approved');--> statement-breakpoint
CREATE INDEX "verification_documents_queue_idx" ON "verification_documents" USING btree ("organization_id","status","submitted_at");--> statement-breakpoint
CREATE INDEX "verification_documents_membership_kind_idx" ON "verification_documents" USING btree ("membership_id","document_kind");--> statement-breakpoint
CREATE INDEX "verification_documents_expiry_idx" ON "verification_documents" USING btree ("status","expires_at");
--> statement-breakpoint
-- Permission seed for the WP-04 resources.
--
-- Every permission is an EXPLICIT `resource[.subresource]:action[:scope]` triple.
-- No `*` action is introduced: `permissionMatches` treats `*` as matching any
-- action, so a single wildcard would silently grant every action added by a
-- later work package. Migrations 0009 and 0010 removed the last wildcard for
-- exactly that reason, and re-adding one here would undo that work.
--
-- Scope choices follow `policy-matrix.md`:
--   `own`          the authenticated profile is the subject of the row;
--   `assigned`     an active, time-valid care assignment exists;
--   `organization` an active organization membership plus matching row ownership;
--   `global`       seeded platform administration only;
--   omitted        evaluated against the object's own relationship policy
--                  (used by `doctor.profile:read`, the approved public view).
INSERT INTO permissions (permission_id, description)
VALUES
  ('verification.document:read:own', 'Read the authenticated profile''s own verification documents and their status'),
  ('verification.document:submit:own', 'Upload and submit a verification document for the authenticated profile''s membership'),
  ('verification.document:read:organization', 'Read verification documents submitted within the organization'),
  ('verification.document:review:organization', 'Approve, reject, request changes to, or suspend a verification document in the organization'),
  ('verification.document:read:global', 'Read verification documents in any organization'),
  ('verification.document:review:global', 'Review verification documents in any organization'),
  ('file.object:read:own', 'Read a private stored object owned by the authenticated profile'),
  ('file.object:read:assigned', 'Read a private stored object belonging to an assigned patient'),
  ('file.object:read:organization', 'Read a private stored object owned by the organization'),
  ('file.object:read:global', 'Read a private stored object in any organization'),
  ('consent.grant:read:own', 'Read consent grants the authenticated profile granted or received'),
  ('consent.grant:create:own', 'Grant consent over the authenticated profile''s own records'),
  ('consent.grant:revoke:own', 'Revoke a consent grant the authenticated profile granted'),
  ('consent.grant:read:assigned', 'Read consent grants covering an assigned patient'),
  ('consent.grant:read:organization', 'Read consent grant metadata recorded within the organization'),
  ('consent.grant:read:global', 'Read consent grant metadata in any organization'),
  ('care.assignment:read:own', 'Read care assignments naming the authenticated profile as patient'),
  ('care.assignment:read:assigned', 'Read care assignments held by the authenticated clinician membership'),
  ('care.assignment:read:organization', 'Read care assignments made within the organization'),
  ('care.assignment:create:organization', 'Assign a clinician to a patient within the organization'),
  ('care.assignment:revoke:organization', 'End a care assignment within the organization'),
  ('care.assignment:read:global', 'Read care assignments in any organization'),
  ('care.assignment:create:global', 'Assign a clinician to a patient in any organization'),
  ('care.assignment:revoke:global', 'End a care assignment in any organization'),
  ('profile.clinical:read:own', 'Read the authenticated profile''s own allergies and conditions'),
  ('profile.clinical:write:own', 'Record or retire the authenticated profile''s own allergies and conditions'),
  ('profile.clinical:read:assigned', 'Read allergies and conditions of an assigned patient'),
  ('profile.clinical:write:assigned', 'Record or retire allergies and conditions for an assigned patient'),
  ('profile.address:read:own', 'Read the authenticated profile''s own addresses'),
  ('profile.address:write:own', 'Create, update, archive or re-designate the authenticated profile''s own addresses'),
  ('profile.emergency_contact:read:own', 'Read the authenticated profile''s own emergency contacts'),
  ('profile.emergency_contact:write:own', 'Create, update, reorder or archive the authenticated profile''s own emergency contacts'),
  ('doctor.profile:read', 'Read the approved doctor professional profile view permitted for this actor'),
  ('doctor.profile:update:own', 'Update the authenticated doctor''s own professional profile, specialties, languages and fee'),
  ('doctor.profile:update:organization', 'Update a doctor professional profile within the organization'),
  ('doctor.profile:update:global', 'Update a doctor professional profile in any organization')
ON CONFLICT (permission_id) DO UPDATE
SET description = EXCLUDED.description;--> statement-breakpoint
-- Role grants. Deliberate omissions, each traceable to `policy-matrix.md`:
--   * `admin` receives NO `profile.clinical:*` permission. Administrative rank
--     grants administrative metadata, not clinical payloads.
--   * `super_admin` likewise receives no clinical permission; global scope is
--     platform administration and never overrides clinical object policy.
--   * `driver`, `pharmacy` and `emergency` receive document and own-profile
--     permissions only; their clinical access arrives through their own work
--     packages with their own reviewed relationships.
INSERT INTO role_permissions (role_id, permission_id)
VALUES
  ('patient', 'verification.document:read:own'),
  ('patient', 'verification.document:submit:own'),
  ('patient', 'file.object:read:own'),
  ('patient', 'consent.grant:read:own'),
  ('patient', 'consent.grant:create:own'),
  ('patient', 'consent.grant:revoke:own'),
  ('patient', 'care.assignment:read:own'),
  ('patient', 'profile.clinical:read:own'),
  ('patient', 'profile.clinical:write:own'),
  ('patient', 'profile.address:read:own'),
  ('patient', 'profile.address:write:own'),
  ('patient', 'profile.emergency_contact:read:own'),
  ('patient', 'profile.emergency_contact:write:own'),
  ('patient', 'doctor.profile:read'),
  ('doctor', 'verification.document:read:own'),
  ('doctor', 'verification.document:submit:own'),
  ('doctor', 'file.object:read:own'),
  ('doctor', 'file.object:read:assigned'),
  ('doctor', 'consent.grant:read:assigned'),
  ('doctor', 'care.assignment:read:assigned'),
  ('doctor', 'profile.clinical:read:assigned'),
  ('doctor', 'profile.clinical:write:assigned'),
  ('doctor', 'profile.address:read:own'),
  ('doctor', 'profile.address:write:own'),
  ('doctor', 'profile.emergency_contact:read:own'),
  ('doctor', 'profile.emergency_contact:write:own'),
  ('doctor', 'doctor.profile:read'),
  ('doctor', 'doctor.profile:update:own'),
  ('driver', 'verification.document:read:own'),
  ('driver', 'verification.document:submit:own'),
  ('driver', 'file.object:read:own'),
  ('driver', 'profile.address:read:own'),
  ('driver', 'profile.address:write:own'),
  ('driver', 'profile.emergency_contact:read:own'),
  ('driver', 'profile.emergency_contact:write:own'),
  ('pharmacy', 'verification.document:read:own'),
  ('pharmacy', 'verification.document:submit:own'),
  ('pharmacy', 'file.object:read:own'),
  ('pharmacy', 'profile.address:read:own'),
  ('pharmacy', 'profile.address:write:own'),
  ('pharmacy', 'profile.emergency_contact:read:own'),
  ('pharmacy', 'profile.emergency_contact:write:own'),
  ('emergency', 'verification.document:read:own'),
  ('emergency', 'verification.document:submit:own'),
  ('emergency', 'file.object:read:own'),
  ('emergency', 'profile.address:read:own'),
  ('emergency', 'profile.address:write:own'),
  ('emergency', 'profile.emergency_contact:read:own'),
  ('emergency', 'profile.emergency_contact:write:own'),
  ('admin', 'verification.document:read:organization'),
  ('admin', 'verification.document:review:organization'),
  ('admin', 'file.object:read:organization'),
  ('admin', 'consent.grant:read:organization'),
  ('admin', 'care.assignment:read:organization'),
  ('admin', 'care.assignment:create:organization'),
  ('admin', 'care.assignment:revoke:organization'),
  ('admin', 'doctor.profile:read'),
  ('admin', 'doctor.profile:update:organization'),
  ('admin', 'profile.address:read:own'),
  ('admin', 'profile.address:write:own'),
  ('admin', 'profile.emergency_contact:read:own'),
  ('admin', 'profile.emergency_contact:write:own'),
  ('super_admin', 'verification.document:read:global'),
  ('super_admin', 'verification.document:review:global'),
  ('super_admin', 'file.object:read:global'),
  ('super_admin', 'consent.grant:read:global'),
  ('super_admin', 'care.assignment:read:global'),
  ('super_admin', 'care.assignment:create:global'),
  ('super_admin', 'care.assignment:revoke:global'),
  ('super_admin', 'doctor.profile:read'),
  ('super_admin', 'doctor.profile:update:global')
ON CONFLICT (role_id, permission_id) DO NOTHING;--> statement-breakpoint
-- Post-seed least-privilege assertion. A wildcard action reaching any of the
-- WP-04 resources would re-open the hole that 0009/0010 closed, and a typo in a
-- role grant above would leave a role permanently short of authority. Both are
-- cheap to check here and expensive to discover in production.
DO $$
DECLARE
  wildcard_permissions text;
  clinical_admin_grants text;
BEGIN
  SELECT COALESCE(string_agg(candidate.permission_id, ', ' ORDER BY candidate.permission_id), '')
  INTO wildcard_permissions
  FROM (
    SELECT permission_id FROM permissions WHERE permission_id LIKE '%:*:%' OR permission_id LIKE '%:*'
  ) AS candidate
  WHERE candidate.permission_id LIKE 'verification.document:%'
     OR candidate.permission_id LIKE 'file.object:%'
     OR candidate.permission_id LIKE 'consent.grant:%'
     OR candidate.permission_id LIKE 'care.assignment:%'
     OR candidate.permission_id LIKE 'profile.clinical:%'
     OR candidate.permission_id LIKE 'profile.address:%'
     OR candidate.permission_id LIKE 'profile.emergency_contact:%'
     OR candidate.permission_id LIKE 'doctor.profile:%';

  IF wildcard_permissions <> '' THEN
    RAISE EXCEPTION
      'Migration 0011 aborted: wildcard action permission(s) present for WP-04 resources: %. A `*` action matches every present and future action; seed explicit per-action permissions instead.',
      wildcard_permissions;
  END IF;

  -- Administrative rank must not confer clinical payload access. If a future
  -- edit grants a clinical permission to `admin` or `super_admin`, fail here
  -- rather than shipping it.
  SELECT COALESCE(string_agg(role_id || ' -> ' || permission_id, ', ' ORDER BY role_id, permission_id), '')
  INTO clinical_admin_grants
  FROM role_permissions
  WHERE role_id IN ('admin', 'super_admin')
    AND permission_id LIKE 'profile.clinical:%';

  IF clinical_admin_grants <> '' THEN
    RAISE EXCEPTION
      'Migration 0011 aborted: administrative role(s) were granted clinical permissions: %. policy-matrix.md denies clinical payload access to admin and super_admin.',
      clinical_admin_grants;
  END IF;
END;
$$;--> statement-breakpoint
-- New `profiles` compatibility component rather than a bump of `identity`.
--
-- `FoundationReadinessRepository` requires an EXACT version match for the
-- components it checks (`foundation` and `identity`), so bumping `identity`
-- without changing `IDENTITY_SCHEMA_VERSION` in the same deployment makes
-- readiness report 503. Nothing in the shipped identity code path changes here:
-- this migration only adds tables and additive permission rows. Registering the
-- WP-04 data model under its own component records the schema level without
-- coupling it to identity readiness, and leaves `IDENTITY_SCHEMA_VERSION`
-- untouched at 6.
INSERT INTO schema_compatibility (component, version)
VALUES ('profiles', 1)
ON CONFLICT (component) DO UPDATE
SET version = EXCLUDED.version, updated_at = now();
