#!/usr/bin/env python3
"""
Flash one SmartCura ESP32 with per-device credentials.

Reads the common values (WiFi, MQTT broker, timezone) from the existing
`smartcura_vitals_monitor/secrets.h`, temporarily replaces the device ID and
MQTT password with the new ones, uploads, then restores the original file.

Usage example:
    python iot-firmware/flash-device.py \
        --device-id 01912345-6789-7abc-8def-0123456789ab \
        --provisioning-secret "your-long-secret" \
        --port COM7
"""

import argparse
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent
SRC_DIR = ROOT / "smartcura_vitals_monitor"
SECRETS = SRC_DIR / "secrets.h"
TEMPLATE = SRC_DIR / "secrets.h.example"
BACKUP = SRC_DIR / "secrets.h.bak"

UUID_V7_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
)


def _read_macros(path: pathlib.Path) -> dict:
    macros: dict = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"#define\s+(\w+)\s+(.*)", line.strip())
        if not match:
            continue
        key = match.group(1)
        value = match.group(2).strip()
        if value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        macros[key] = value
    return macros


def _write_secrets(macros: dict, device_id: str, provisioning_secret: str, provisioning_pin: str) -> None:
    required = {"WIFI_SSID", "WIFI_PASSWORD", "MQTT_HOST", "MQTT_PORT", "TZ_OFFSET_MIN"}
    missing = required - macros.keys()
    if missing:
        raise SystemExit(f"Missing common values in secrets template: {sorted(missing)}")

    lines = [
        "/* SmartCura vitals monitor - per-device secrets.",
        " * Auto-generated by flash-device.py. Do not commit.",
        " */",
        "#ifndef SMARTCURA_SECRETS_H",
        "#define SMARTCURA_SECRETS_H",
        "",
        f'#define WIFI_SSID       "{macros["WIFI_SSID"]}"',
        f'#define WIFI_PASSWORD   "{macros["WIFI_PASSWORD"]}"',
        f'#define MQTT_HOST       "{macros["MQTT_HOST"]}"',
        f'#define MQTT_PORT       {macros["MQTT_PORT"]}',
        f'#define DEVICE_ID       "{device_id}"',
        "#define MQTT_USERNAME   DEVICE_ID",
        f'#define MQTT_PASSWORD   "{provisioning_secret}"',
        f'#define PROVISIONING_PIN "{provisioning_pin}"',
        f'#define TZ_OFFSET_MIN   {macros["TZ_OFFSET_MIN"]}',
        "",
        "#endif // SMARTCURA_SECRETS_H",
        "",
    ]
    SECRETS.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Flash one SmartCura ESP32 with its own credentials."
    )
    parser.add_argument("--device-id", required=True, help="UUIDv7 returned by POST /organizations/{org}/devices")
    parser.add_argument("--provisioning-secret", required=True, help="The provisioning secret for this device")
    parser.add_argument("--provisioning-pin", required=True, help="8-digit PIN printed on the device sticker")
    parser.add_argument("--port", default=None, help="Upload port, e.g. COM7 or /dev/ttyUSB0")
    parser.add_argument("--no-restore", action="store_true", help="Keep the generated secrets.h after upload")
    args = parser.parse_args()

    if not UUID_V7_RE.match(args.device_id):
        print(f"ERROR: device-id must be a lowercase UUIDv7: {args.device_id}", file=sys.stderr)
        return 1
    if len(args.provisioning_secret) < 32:
        print("ERROR: provisioning-secret must be at least 32 characters", file=sys.stderr)
        return 1
    if not re.fullmatch(r"^\d{8}$", args.provisioning_pin):
        print("ERROR: provisioning-pin must be exactly 8 digits", file=sys.stderr)
        return 1

    source = SECRETS if SECRETS.exists() else TEMPLATE
    if not source.exists():
        print(f"ERROR: neither {SECRETS} nor {TEMPLATE} exists", file=sys.stderr)
        return 1

    macros = _read_macros(source)

    if not BACKUP.exists():
        shutil.copy2(source, BACKUP)

    _write_secrets(macros, args.device_id, args.provisioning_secret, args.provisioning_pin)
    print(f"[flash] wrote secrets.h for device {args.device_id}")

    cmd = ["pio", "run", "-d", str(ROOT), "-t", "upload"]
    if args.port:
        cmd += ["--upload-port", args.port]
    print(f"[flash] running: {' '.join(cmd)}")

    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError as e:
        print(f"[flash] upload failed with exit code {e.returncode}", file=sys.stderr)
        return e.returncode
    finally:
        if not args.no_restore and BACKUP.exists():
            shutil.copy2(BACKUP, SECRETS)
            BACKUP.unlink()
            print("[flash] restored original secrets.h")

    print("[flash] done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
