'use client';
import { useMemo, useState } from 'react';
import { useAuth } from '@/hooks/use-auth';
import { useApiResource } from '@/hooks/use-api-resource';
import ResourceState from '@/components/data/ResourceState';
import TopBar from '@/components/layout/TopBar';
import { listAuditLogs } from '@/lib/api/workstream-f';
export default function AuditLogsPage() {
 const { activeMembership, isLoading: authLoading }=useAuth(); const organizationId=activeMembership?.organization_id; const [action,setAction]=useState(''); const [objectType,setObjectType]=useState('');
 const resource=useApiResource(s=>organizationId?listAuditLogs(organizationId,{action:action||undefined,objectType:objectType||undefined,limit:100,signal:s}):Promise.resolve(null),[organizationId,action,objectType]); const rows=useMemo(()=>resource.data?.data??[],[resource.data]);
 if(authLoading)return <div className="p-8 text-slate-500">Loading session...</div>;
 if(!organizationId)return <main className="p-8"><ResourceState isLoading={false} error={null} isEmpty onRetry={resource.reload} loadingLabel="Loading audit logs..." forbiddenTitle="Audit logs unavailable" errorTitle="Audit logs unavailable" emptyTitle="No active organization" emptyBody="Select an active membership before viewing audit logs." emptyIcon="security"/></main>;
 return <main className="flex-1 min-h-screen bg-[#F9FAFB]"><TopBar breadcrumbs={[{label:'Settings'},{label:'Audit logs'}]}/><div className="p-5 sm:p-8 max-w-7xl mx-auto space-y-6"><div><h1 className="text-3xl font-black text-slate-900">Audit logs</h1><p className="text-slate-500 mt-1">Security and administrative events for your active organization.</p></div><div className="bg-white border border-slate-200 rounded-2xl p-4 grid sm:grid-cols-2 gap-3"><input value={action} onChange={e=>setAction(e.target.value)} className="h-11 px-4 rounded-xl bg-slate-50 border border-slate-200" placeholder="Filter by action"/><input value={objectType} onChange={e=>setObjectType(e.target.value)} className="h-11 px-4 rounded-xl bg-slate-50 border border-slate-200" placeholder="Filter by object type"/></div><ResourceState isLoading={resource.isLoading} error={resource.error} isEmpty={!rows.length} onRetry={resource.reload} loadingLabel="Loading audit logs..." forbiddenTitle="You cannot view audit logs" errorTitle="Audit logs could not be loaded" emptyTitle="No audit events found" emptyBody="No events match the current filters." emptyIcon="history"/>{!resource.isLoading&&!resource.error&&rows.length>0&&<div className="bg-white rounded-2xl border border-slate-200 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Occurred</th><th className="p-4">Action</th><th className="p-4">Object</th><th className="p-4">Actor</th><th className="p-4">Reason</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row=><tr key={row.audit_id}><td className="p-4 text-sm text-slate-500">{new Date(row.occurred_at).toLocaleString()}</td><td className="p-4 font-bold text-slate-900">{row.action}</td><td className="p-4 text-sm text-slate-600">{row.object_type}<br/><code className="text-xs text-slate-400">{row.object_id}</code></td><td className="p-4"><code className="text-xs text-slate-500">{row.actor_profile_id}</code></td><td className="p-4 text-sm text-slate-600">{row.reason ?? '—'}</td></tr>)}</tbody></table></div>}</div></main>;
}
